# Python Basics

Links:
- https://www.python.org/
- https://pypi.org/

In [1]:
import math
import numpy as np

## 1st Example: Hello World

In [2]:
print('Coucou :)')

Coucou :)


## Variables and basic types
### Numeric data
- integers: int
- floating numbers: float (https://fr.wikipedia.org/wiki/IEEE_754)

NB: float type is automatically adapted to the architecture (32 or 64 bits)

In [3]:
nb_persons = 4
nb_persons

4

In [4]:
type(nb_persons)

int

In [5]:
temperature = 17.25
temperature

17.25

In [6]:
type(temperature)

float

In [7]:
type('4')

str

In [8]:
type("ceci est 1 texte")

str

In [9]:
nb_persons = 5
nb_persons

5

In [10]:
nb_persons * 10

50

In [11]:
nb_persons_total = nb_persons * 10
nb_persons_total

50

In [12]:
(nb_persons - 3) * 2 + 4 

8

In [13]:
# division => float
nb_persons_total / 12

4.166666666666667

In [14]:
# quotient
nb_persons_total // 12

4

In [15]:
# reminder:
nb_persons_total % 12

2

In [16]:
# quotient + reminder
divmod(nb_persons_total, 12)

(4, 2)

In [17]:
nb_persons_total

50

In [18]:
# power operator
2**10

1024

In [19]:
# 1/16e
2**-4

0.0625

In [20]:
# weird computation: float, int -> float
temperature + nb_persons

22.25

#### `math` module
This module from the standard library provides mathematical functions and constants

In [21]:
math.ceil(math.sqrt(temperature))

5

In [22]:
math.ceil

<function math.ceil(x, /)>

In [23]:
math.ceil?

Signature: math.ceil(x, /)
Docstring:
Return the ceiling of x as an Integral.

This is the smallest integer >= x.
Type:      builtin_function_or_method

In [24]:
math.pi

3.141592653589793

#### Float precision

In [25]:
# base 2: 0.000110011001100110011001100110011...
price = 0.1
price

0.1

In [26]:
2*price

0.2

In [27]:
3*price

0.30000000000000004

#### Special floats

In [28]:
# very big number as a float
big_number = 1E308
big_number

1e+308

In [29]:
x = big_number * 2
x

inf

In [30]:
1E-308

1e-308

In [31]:
x / x

nan

In [32]:
float('inf')

inf

In [33]:
math.inf

inf

In [34]:
math.nan

nan

In [35]:
0 * math.nan

nan

In [36]:
2**64 - 1

18446744073709551615

In [37]:
big_counter = 123000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004
big_counter

123000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004

In [38]:
big_counter + 1

123000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005

#### Numpy alternative
- integers: int8, int16, int32, int64, ..., uint8, uint16, ...
- floats: float32, float64, ...

In [39]:
data = np.ones(8, dtype='uint8')
data

array([1, 1, 1, 1, 1, 1, 1, 1], dtype=uint8)

In [40]:
value = 255
type(value)

int

In [41]:
data[0] = value
data

array([255,   1,   1,   1,   1,   1,   1,   1], dtype=uint8)

In [42]:
print(data)

[255   1   1   1   1   1   1   1]


In [43]:
data.dtype

dtype('uint8')

### Text
type str

In [44]:
city1 = 'Saint-Orens-de-Gameville'
city2 = "Revel"
city3 = 'Roquettes'
city4 = "Pau"

In [45]:
"Aujourd'hui"

"Aujourd'hui"

In [46]:
text = 'Aujourd\'hui, je dis: "il fait beau !"'
text

'Aujourd\'hui, je dis: "il fait beau !"'

In [47]:
print(text)

Aujourd'hui, je dis: "il fait beau !"


In [48]:
type(city1)

str

In [49]:
# concatenate: +
city1 + ', ' + city2

'Saint-Orens-de-Gameville, Revel'

In [50]:
city1[0]

'S'

In [51]:
n = len(city1)
n

24

In [52]:
city1[n-1]

'e'

In [53]:
# city1[n]
# => IndexError: string index out of range

In [54]:
# last character
city1[-1]

'e'

In [55]:
city1[-n]

'S'

In [59]:
# TypeError: 'str' object does not support item assignment
# city1[0] = 'T'

#### Slices

In [56]:
print(city1[:6])
print(city1[6:11])
print(city1[11:])

Saint-
Orens
-de-Gameville


In [57]:
# slice with step
print(city1[3:20:2])
print(city1[::2]) # even indexes
print(city1[1::2]) # odd indexes
print(city1[::-1])

n-rn-eGmv
SitOesd-aeil
an-rn-eGmvle
ellivemaG-ed-snerO-tniaS


In [58]:
# slices are working with numpy arrays too
data[::-1]

array([  1,   1,   1,   1,   1,   1,   1, 255], dtype=uint8)

In [60]:
# Solution: create a new string
'T' + city1[1:]

'Taint-Orens-de-Gameville'

In [61]:
# shared reference
city1bis = city1
city1bis

'Saint-Orens-de-Gameville'

In [62]:
# city1 references the new string
city1 = 'T' + city1[1:]
city1

'Taint-Orens-de-Gameville'

In [63]:
print(city1)
print(city1bis)

Taint-Orens-de-Gameville
Saint-Orens-de-Gameville


#### Methods of type str
Try these ones:
- split
- lower, upper
- startswith, endswith, contains?
- find, index

In [64]:
words = city1bis.split('-')
words

['Saint', 'Orens', 'de', 'Gameville']

In [65]:
type(words)

list

In [66]:
city1.index('de')

12

In [67]:
city1bis.upper()

'SAINT-ORENS-DE-GAMEVILLE'

In [68]:
# NB: contains is not a str method => operator 'in'
'de' in city1 

True

In [69]:
city1.endswith('z')

False

### Boolean
type bool

In [70]:
type(True)

bool

### Summary
Basic types list:

-
-
-


## Containers
- list : []
- tuple : () or nothing
- dict : {}
- set : {}

### Lists
- type `list`
- build with `[]` or function `list`

In [1]:
cities = [city1bis, city2, city3, city4]
cities

NameError: name 'city1bis' is not defined

In [72]:
type(cities)

list

#### Foreach loop

In [73]:
for city in cities:
    print(city)

Saint-Orens-de-Gameville
Revel
Roquettes
Pau


In [74]:
print('City number:', len(cities))
print()
for city in cities:
    print(city)
    print(' - upper:', city.upper())
    print(' - starts with R:', city.startswith('R'))

City number: 4

Saint-Orens-de-Gameville
 - upper: SAINT-ORENS-DE-GAMEVILLE
 - starts with R: False
Revel
 - upper: REVEL
 - starts with R: True
Roquettes
 - upper: ROQUETTES
 - starts with R: True
Pau
 - upper: PAU
 - starts with R: False


In [75]:
print(city1bis, city2, city3, city4)

Saint-Orens-de-Gameville Revel Roquettes Pau


In [76]:
print(city1bis, city2, city3, city4, sep=', ')

Saint-Orens-de-Gameville, Revel, Roquettes, Pau


### Iterable
An iterable object defines an implicit iteration on its elements
- All python containers are iterable
- Strings are iterable
- a Range object

In [77]:
for letter in city1bis:
    print(letter, end='   ')

S   a   i   n   t   -   O   r   e   n   s   -   d   e   -   G   a   m   e   v   i   l   l   e   

In [78]:
for i in range(1, 11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [79]:
for i in range(10):
    print(i + 1)

1
2
3
4
5
6
7
8
9
10


In [80]:
# 10 downto 0
for i in range(10, -1, -1):
    print(i)

10
9
8
7
6
5
4
3
2
1
0


In [81]:
for i in range(10, 0, -1):
    print(i)
print('Boom')

10
9
8
7
6
5
4
3
2
1
Boom


### Builtin functions on Iterables

In [82]:
list(city1bis)

['S',
 'a',
 'i',
 'n',
 't',
 '-',
 'O',
 'r',
 'e',
 'n',
 's',
 '-',
 'd',
 'e',
 '-',
 'G',
 'a',
 'm',
 'e',
 'v',
 'i',
 'l',
 'l',
 'e']

In [83]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [84]:
list(cities)

['Saint-Orens-de-Gameville', 'Revel', 'Roquettes', 'Pau']

In [85]:
# builtin function list masked by a variable with same name
list = [1,2,3]
list

[1, 2, 3]

In [86]:
# delete variable
del list

In [87]:
# back to the true 'list'
list(range(5))

[0, 1, 2, 3, 4]

In [88]:
for i, city in enumerate(cities):
    print(i, city)

0 Saint-Orens-de-Gameville
1 Revel
2 Roquettes
3 Pau


In [89]:
for i, city in enumerate(cities, start=1):
    print(i, city)

1 Saint-Orens-de-Gameville
2 Revel
3 Roquettes
4 Pau


In [90]:
for i, letter in enumerate(city1bis):
    print(i, letter)

0 S
1 a
2 i
3 n
4 t
5 -
6 O
7 r
8 e
9 n
10 s
11 -
12 d
13 e
14 -
15 G
16 a
17 m
18 e
19 v
20 i
21 l
22 l
23 e


In [91]:
list(enumerate('seasons'))

[(0, 's'), (1, 'e'), (2, 'a'), (3, 's'), (4, 'o'), (5, 'n'), (6, 's')]

In [92]:
seasons = ['summer', 'fall', 'winter', 'spring']
list(enumerate(seasons))

[(0, 'summer'), (1, 'fall'), (2, 'winter'), (3, 'spring')]

In [93]:
# enumerate is lazy
e = enumerate(seasons)
e

In [94]:
list(e)

[(0, 'summer'), (1, 'fall'), (2, 'winter'), (3, 'spring')]

In [95]:
sum([1,2,3])

6

In [96]:
# sum numbers from 1 to 10
sum(range(1, 11))

55

In [97]:
max(range(1, 11))

10

In [98]:
min(range(1, 11))

1

In [99]:
min(cities)

'Pau'

In [100]:
cities.append('Albertville')
cities.append('Zalana ')
cities

['Saint-Orens-de-Gameville',
 'Revel',
 'Roquettes',
 'Pau',
 'Albertville',
 'Zalana ']

In [103]:
min(cities), max(cities)

('Albertville', 'Zalana ')

In [105]:
print(12 < 5) # integer order
print('12' < '5') # str order

False
True


In [107]:
sorted(range(10, 0, -1))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [108]:
sorted(cities)

['Albertville',
 'Pau',
 'Revel',
 'Roquettes',
 'Saint-Orens-de-Gameville',
 'Zalana ']

In [115]:
words = [
    'été', 'étage', 'étuve',
    'abricot', 'Appareil',
    'cœur', 'cobra', 'corde',
    'Zèbre', 'zoo',
    'ça', 'carte', 'caisse'
]

In [116]:
sorted(words)

['Appareil',
 'Zèbre',
 'abricot',
 'caisse',
 'carte',
 'cobra',
 'corde',
 'cœur',
 'zoo',
 'ça',
 'étage',
 'étuve',
 'été']